<!doctype html>

<head>
  <title>WhatPulse Stats</title>
  <link rel="stylesheet" href="./assets/css/main.css" type="text/css" />
</head>

<body>
  <header>
    <div><h1>WhatPulse Stats</h1></div>
    <nav><a class="cl-effect-15" href="./user">User Stats</a><a>Team Stats</a><a>Compare</a></nav>
  </header>
<main>
  <div class="Grid Grid--gutters Grid--flexCells">
  <div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
<div class="Grid-cell"><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nec massa neque. Ut rhoncus mauris id ipsum aliquet pharetra. Pellentesque id velit ultricies, tempor dolor eget, aliquet tellus. Vivamus risus sapien, ultricies non augue eget, pellentesque rutrum dui. Vivamus pretium magna orci, non lobortis sem vehicula eget. Etiam id nisl eu mi lobortis tincidunt ut eu lectus. Donec gravida eleifend semper. Donec in lorem sit amet turpis ultrices posuere. In suscipit ultrices sem vel tincidunt. Proin viverra neque in arcu mollis, sed pretium sem varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur lobortis mi enim, sed molestie ante egestas ac. Nullam ut pellentesque tortor. Phasellus nec est orci.</div></div>
  <div class="Grid-cell"><div>Sed sed turpis libero. Quisque non lacus vel velit vestibulum lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam scelerisque, augue bibendum porta faucibus, elit nisl semper felis, sed porttitor orci orci nec urna. Vivamus at sem lacinia, porttitor neque ac, scelerisque massa. Praesent lorem lorem, varius eu massa vitae, viverra lobortis augue. Cras luctus diam eu felis sodales, vitae blandit nibh scelerisque. Nam malesuada dui ut arcu sollicitudin fringilla ultricies ut velit. Sed eu odio auctor, euismod ipsum vitae, blandit nibh. Fusce et feugiat sapien. Nulla vitae justo turpis. Quisque aliquet, turpis ac euismod aliquam, mi augue tincidunt tellus, mattis tempor nibh lectus non augue. Phasellus nec sagittis sem, at vehicula justo. Ut pretium lorem malesuada molestie placerat. Nullam vel erat ut ligula varius ultricies.</div></div>
  <div class="Grid-cell"><div>Nullam neque massa, aliquam at tellus nec, ultricies venenatis augue. Donec condimentum commodo tincidunt. Etiam quis imperdiet nisi, sed ultrices sapien. Mauris auctor augue ac malesuada gravida. Phasellus tincidunt, lectus vel consectetur imperdiet, eros lacus adipiscing lacus, nec aliquam nulla diam interdum urna. Nulla risus libero, scelerisque eget augue sit amet, egestas mollis leo. Nam sollicitudin neque tellus, sodales sodales ligula auctor dictum. Aliquam velit metus, lobortis ac quam non, tincidunt varius nulla. Maecenas condimentum consequat sem, eget pharetra tortor. Integer at pharetra nibh, id consectetur metus. Integer id nisl gravida, gravida quam id, semper erat.</div></div>
</div>
<section class="ha-waypoint" data-animate-down="ha-header-small" data-animate-up="ha-header-large">
    <!-- ... -->
</section>
</main>
<footer>
Hi
</footer>

<script>
var cbpAnimatedHeader = (function() {
 
    var docElem = document.documentElement,
        header = document.querySelector( '.cbp-af-header' ),
        didScroll = false,
        changeHeaderOn = 300;
 
    function init() {
        window.addEventListener( 'scroll', function( event ) {
            if( !didScroll ) {
                didScroll = true;
                setTimeout( scrollPage, 250 );
            }
        }, false );
    }
 
    function scrollPage() {
        var sy = scrollY();
        if ( sy >= changeHeaderOn ) {
            classie.add( header, 'cbp-af-header-shrink' );
        }
        else {
            classie.remove( header, 'cbp-af-header-shrink' );
        }
        didScroll = false;
    }
 
    function scrollY() {
        return window.pageYOffset || docElem.scrollTop;
    }
 
    init();
 
})();
</script>
</body>
